### ISSUE TITLE
add support for windows key (Keys.LWin)

### ISSUE THREAD

**Issue by jamesmanning** [NimbleTools/Clipupload#3]
looks like it'd need a decent chunk of change, but I can try to tackle it if you're ok with the idea.

It's mainly because I have the Win+S muscle memory from OneNote and would love to be able to use that even on machines without OneNote installed, using ClipUpload for me 'get sshot of part of the screen into the clipboard' needs. :smile:

**Comment by codecat** [comment]
I think this requires the application to be running with elevated permissions (eg. run as administrator).

**Comment by jamesmanning** [comment]
@AngeloG AFAICT it doesn't - OneNote binds Win+S (old versions) and Win+Shift+S (newer versions) and I just checked with process explorer to confirm it's not running elevated.

I'll try now to just hack an existing addon to have it bind to the requested hotkey with LWin added and see if it works.

**Comment by jamesmanning** [comment]
Nevermind - the source for System.Windows.Forms.Control.ModifierKeys shows it's only going to support Shift/Control/Alt, so no such luck. :smile: 

Oh, well.

**Comment by jamesmanning** [comment]
It looks like I can use autohotkey to bind Win+S and translate it to whatever hotkey I want to assign to the clipupload plugin in question.  That'll be sufficient for my needs. :smile: 

https://www.autohotkey.com/docs/misc/Override.htm

Looks like this is in a foo.ahk file is sufficient to have Win+S remap to Ctrl+Shift+Alt+S, which I then have bound in ClipUpload:

```
#s::
Send !+^s
return
```
